name: tic_tac_toe_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# All dependencies should be at the same indentation level.
dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.5 # For state management (the ViewModel pattern)
  shared_preferences: ^2.2.2 # For saving scores

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

